name: Build Auto-signed APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk nodejs npm keytool
        
    - name: Install and build with auto-signing
      run: |
        npm install -g @bubblewrap/cli
        
        # 自动生成签名密钥
        keytool -genkey -noprompt \
          -keystore mykey.jks \
          -alias mykey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=Beijing Time, OU=Android, O=Wekh, C=CN"
        
        # 初始化并构建
        bubblewrap init --manifest=https://time.wekh.eu.org/manifest.json --non-interactive
        cd $(ls -d */ | head -n 1)
        bubblewrap build --jks=../mykey.jks --alias=mykey --key-pass=123456 --store-pass=123456
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beijing-time-app
        path: "*/app-release-signed.apk"
