name: Build Auto-signed APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Generate signing key
      run: |
        keytool -genkey -noprompt \
          -keystore mykey.jks \
          -alias mykey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass 123456 \
          -keypass 123456 \
          -dname "CN=Beijing Time, OU=Android, O=Wekh, C=CN"
        
    - name: Initialize and build
      run: |
        echo "y" | bubblewrap init --manifest=https://time.wekh.eu.org/manifest.json
        cd $(ls -d */ | head -n 1)
        bubblewrap build --jks=../mykey.jks --alias=mykey --key-pass=123456 --store-pass=123456
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: beijing-time-app
        path: "*/app-release-signed.apk"
